# ISOLATED VG EXTENSION, generated by build_gate_mean.py.
# p[:11] retains accepted-state meanings; p[11]=VG, p[12]=channel-II switch/scale.
# No bell/Gaussian output curve imposed. No fit parameter changes across VG.
# Local channel-II uses shared drain-depletion M; separate surface field unknown.
# Generated from frozen v3 mean; see derivative_manifest.json.
# Two explicit conditional couplings:
# phi_gidl: additional local voltage drop across the drain-edge tunneling field.
# phi_emitter: modulation of the emitter minority-hole diffusion prefactor.
# Neither is random output-voltage jitter. These local couplings are hypotheses,
# not a self-consistent 2D Poisson solution or identified defect positions.
"""Photo-extended copy of gate_mean.py: p[13] = photogeneration current I_PH (A). Original untouched.
Current-carrying quasi-neutral candidate with asymmetric density-dependent SRH.
Local emitter/collector quasi-Fermi voltage partition includes the neutral-base hole drop.
Auger is explicitly absent; effective lifetime cannot separate bulk/interface.

The carrier-partition drift term is included using a shooting solution.
This is not a full Poisson/degenerate/field-mobility model. Access excess is assumed
equal to the mean base excess, a separate unverified quasi-static closure.
Source/drain depletion widths retain abrupt-junction low-injection electrostatics.
No stochastic jitter or fitted readout current floor is present.
"""
from pathlib import Path
import sys,time,json
import numpy as np
from numba import njit
HERE=Path(__file__).resolve().parent
CAL=Path(__file__).resolve().parents[1]/'model'/'janus_calibration_20260920'
sys.path.insert(0,str(CAL/'idvd_model'))
from mean_model import Field,Q,VT,AREA_CM2,LENGTH_M,WIDTH_M,TSI_M,COX_F,NI_CM3,CHANNEL,BB_A,BB_B,EPS0

sys.path.insert(0,str(CAL/'high_injection_review'))
from current_carrying_transport import integrate as transport_integrate
sys.path.insert(0,str(CAL/'idvd_model_v3'))
from srh_transport import solve_voltage as srh_solve
DN=450*VT;DP=150*VT
LOG_Y=np.linspace(-14,4,241)
LOG_K=np.linspace(-3,1,161)

@njit(cache=True)
def transport_solve_full(h_end,M,b,kappa,r=1/3,steps=64):
    # Same current-carrying sensitivity solver, with relative tolerance that
    # remains meaningful in the equilibrium, very-low-injection limit.
    if h_end==0 and b==0:return 0.,0.,0.,0
    j0=max(2*h_end-np.log1p(h_end),1e-100)
    for it in range(24):
        h,je,deriv,qavg=transport_integrate(j0,M,b,kappa,r,steps)
        if not np.isfinite(h) or deriv<=0:return np.nan,np.nan,np.nan,it
        residual=h-h_end
        if abs(residual)<1e-9*max(h_end,1e-100):return j0,je-j0,qavg,it+1
        j0=max(j0*.1,j0-residual/deriv)
    return np.nan,np.nan,np.nan,24

@njit(cache=True)
def transport_solve(h_end,M,b,kappa,r=1/3,steps=64):
    if h_end<1e-8:
        k=np.sqrt(kappa)
        if k<1e-6:
            j0=h_end*(1-kappa/6);qa=h_end*(.5-kappa/24)
        else:
            j0=h_end*k/np.sinh(k)
            qa=h_end*2*np.sinh(k/2)**2/(k*np.sinh(k))
        if M*j0+b<1e-8:return j0,kappa*qa,qa,0
    return transport_solve_full(h_end,M,b,kappa,r,steps)

@njit(cache=True)
def hn(y,t):
    # H(y*t)/(DN*y*y), H(z)=integral_0^z Da(s)*s ds.
    dc=DN+DP;ginf=2*DP/dc;z=dc/DP*y*t
    if z<1e-3:
        ratio=(dc/DP*t)**2*(.5-z/3+z*z/4-z*z*z/5+z**4/6)
    else:ratio=(z-np.log1p(z))/(y*y)
    coeff=DP*DP*(DN-DP)/(dc**3)
    return ginf*t*t/2+coeff*ratio

@njit(cache=True)
def make_table(ly,lk,t,w):
    out=np.empty((len(ly),len(lk),3))
    for i in range(len(ly)):
        y=10**ly[i]
        for j in range(len(lk)):
            k=10**lk[j];lo=-35.;hi=0.
            for _ in range(48):
                z=(lo+hi)/2;a=np.exp(z);val=0.
                for h in range(len(t)):
                    g=(1+2*y*t[h])/(1+(1+DN/DP)*y*t[h])
                    val+=w[h]*g/np.sqrt(a*a+2*k*k*hn(y,t[h]))
                if val>1:lo=z
                else:hi=z
            a=np.exp((lo+hi)/2);charge=0.
            for h in range(len(t)):
                g=(1+2*y*t[h])/(1+(1+DN/DP)*y*t[h])
                charge+=w[h]*t[h]*g/np.sqrt(a*a+2*k*k*hn(y,t[h]))
            out[i,j,0]=a
            out[i,j,1]=np.sqrt(a*a+2*k*k*hn(y,1.))
            out[i,j,2]=charge
    return out

@njit(cache=True)
def lookup(y,k,table):
    ay=(np.log10(max(y,1e-14))+14)/18*(table.shape[0]-1)
    ak=(np.log10(max(k,1e-3))+3)/4*(table.shape[1]-1)
    iy=max(0,min(int(ay),table.shape[0]-2));ik=max(0,min(int(ak),table.shape[1]-2))
    fy=max(0.,min(1.,ay-iy));fk=max(0.,min(1.,ak-ik))
    return (1-fy)*((1-fk)*table[iy,ik]+fk*table[iy,ik+1])+fy*((1-fk)*table[iy+1,ik]+fk*table[iy+1,ik+1])

@njit(cache=True)
def f_interp(r,grid,values):
    pos=r/(grid[1]-grid[0]);i=max(0,min(int(pos),len(grid)-2));a=pos-i
    return values[i]*(1-a)+values[i+1]*a

@njit(cache=True)
def components(u,r,p,na,vbi,rg,fg,table):
    # p: beta,tau_bulk,tau_junc,Rcontact,lGIDL_nm,taccess_nm,NAaccess_cm3,Laccess_nm
    beta,tau,tj,rc,lg,ta,naa,la,tau_ratio=p[:9]
    phi_gidl=p[9];phi_emitter=p[10];vg=p[11];channel_II_scale=p[12]
    iph=p[13] if p.shape[0]>13 else 0.   # photogeneration current (A), uniform hole supply into the body
    eps=11.7*EPS0/100
    prod=NI_CM3**2*np.expm1(u/VT)
    delta=2*prod/(na+np.sqrt(na*na+4*prod))
    wd=np.sqrt(2*eps*(vbi+r)/(Q*na))
    # u is local quasi-Fermi splitting. The junction electrostatic reduction
    # is u-VT*log(p_source/NA), not u itself, in this neutrality approximation.
    source_barrier=vbi-u+VT*np.log1p(delta/na)
    if source_barrier<=0:return np.full(19,np.nan)
    ws=np.sqrt(2*eps*source_barrier/(Q*na))
    length=LENGTH_M*100-wd-ws
    if length<=1e-7:return np.full(19,np.nan)
    prod=NI_CM3**2*np.expm1(u/VT)
    delta=2*prod/(na+np.sqrt(na*na+4*prod))
    scale=Q*AREA_CM2*DN*na/length
    mult=1.+(f_interp(r+(p[19] if p.shape[0]>19 else 0.),rg,fg[0])-1.)*np.exp(p[20] if p.shape[0]>20 else 0.)   # p[19]: local junction potential offset (V), p[20]: log-scale of (M-1) [state hypotheses]
    balance=-np.expm1(-r/VT)
    bbj=f_interp(r+(p[19] if p.shape[0]>19 else 0.),rg,fg[1])*balance
    eg=max((u+r-vg-.3-1.12+phi_gidl)/(lg*1e-7),0.)
    depth=min(np.sqrt(2*eps*1.12/(Q*7e19)),TSI_M*100)
    volume=WIDTH_M*100*5e-7*depth
    gidl=Q*volume*BB_A*eg**2.5*np.exp(-BB_B/max(eg,1.))*balance
    # Low-VD IDVG fit frozen; DIBL/body coupling not extracted and not invented.
    n=1.7786684648788609*(1.+(p[16] if p.shape[0]>16 else 0.)*(u+r));ov=vg-(-.49032524444873615)+(p[14] if p.shape[0]>14 else 0.)*(u+r)+(p[15] if p.shape[0]>15 else 0.)*u;pp=ov/n   # p[14] DIBL eta (V/V), p[15] body coupling gamma, p[16] slope degradation kappa (1/V)
    sf=np.log1p(np.exp(pp/(2*VT)));sr=np.log1p(np.exp((pp-u-r)/(2*VT)))
    ch=2*n*7.52135238967614e-5*VT*VT*(sf-sr)*(sf+sr)/(1+.6335606399651017*n*VT*np.log1p(np.exp(ov/(n*VT))))
    # Holes from channel-electron avalanches enter the neutral-body boundary.
    # Direct channel electrons do not flow through the neutral-base BJT solver.
    # High-VD channel seed of this device (floating-body DIBL): I_p*10^((VG+1.8)/S) added to the channel electrons at the drain.
    ch=ch+((p[17]*10.**((vg+1.8)/p[18])) if (p.shape[0]>18 and p[17]>0.) else 0.)
    ii_ch=max(mult-1.,0.)*ch*channel_II_scale
    ii_ph=max(mult-1.,0.)*iph   # photo-electrons collected at the drain also multiply
    # Local avalanche path (microplasma-type) near the drain junction, saturating (negligible in the LRS).
    # p[21] strength, p[22] saturation (A), p[23] log-fluctuation, p[24] carriers it multiplies:
    #   0 = surface/edge definition (GIDL + junction BTBT + channel + photo electrons)
    #   1 = bulk definition (BJT-injected electrons crossing the junction + photo electrons + junction BTBT), channel and surface GIDL excluded
    loc_on=(p.shape[0]>23 and p[21]>0.);bulk=(p.shape[0]>24 and p[24]>0.5)
    iloc=0.
    # optional gate-drain-field dependence of the local path: strength x exp(kappaF*(V_GD - 5.6 V)), p[25] = kappaF (1/V)
    fdep=np.exp(p[25]*((u+r-vg)-5.6)) if p.shape[0]>25 else 1.
    edge_only=(p.shape[0]>24 and 1.5<p[24]<2.5)   # p[24]=2: gate-edge carriers only (GIDL, junction BTBT, photo); channel electrons excluded
    if loc_on and not bulk:iloc=min(p[21]*np.exp(p[23])*fdep*max(mult-1.,0.)*(gidl+bbj+iph+(0. if edge_only else ch)),p[22])
    js,lb,qa,hole_drop_over_VT,iterations=srh_solve(delta/na,mult,(bbj+gidl+ii_ch+iph+ii_ph+iloc)/scale,length*length/(DN*tau),1/3,64,tau_ratio,(1+tau_ratio)*NI_CM3/na)
    if loc_on and bulk and np.isfinite(js):
        for _ in range(3):   # fixed-point iteration: the local path multiplies the self-consistent BJT seed
            iloc=min(p[21]*np.exp(p[23])*max(mult-1.,0.)*(scale*js+iph+bbj),p[22])
            js,lb,qa,hole_drop_over_VT,iterations=srh_solve(delta/na,mult,(bbj+gidl+ii_ch+iph+ii_ph+iloc)/scale,length*length/(DN*tau),1/3,64,tau_ratio,(1+tau_ratio)*NI_CM3/na)
            if not np.isfinite(js):break
    if not np.isfinite(js):return np.full(19,np.nan)
    seed=scale*js;bulk=scale*lb;emitter=seed+bulk
    # Nonlinear SRH integral returned by kernel; bulk is NOT Qpair/tau.
    # Standard low-injection minority-hole diffusion in an n+ emitter.
    # beta is the low-injection reference ratio at fixed zero-bias base length.
    # High-injection base current no longer shares its exp(u/2VT) scaling.
    lref=LENGTH_M*100-2*np.sqrt(2*eps*vbi/(Q*na))
    isp=Q*AREA_CM2*DN*NI_CM3**2/(na*lref*beta)
    diff=isp*np.exp(-phi_emitter/VT)*np.expm1(u/VT)
    junction=Q*AREA_CM2*ws*NI_CM3/(2*tj)*np.expm1(u/(2*VT))
    avg=na*qa
    # Explicit independent access slab. This density-sharing assumption is not Poisson-derived.
    sigma=Q*(450*avg+150*(naa+avg))
    racc=(la*1e-7)/(WIDTH_M*100*ta*1e-7*sigma)
    mult=1.+(f_interp(r+(p[19] if p.shape[0]>19 else 0.),rg,fg[0])-1.)*np.exp(p[20] if p.shape[0]>20 else 0.)   # p[19]: local junction potential offset (V), p[20]: log-scale of (M-1) [state hypotheses]
    ii=(mult-1)*seed
    # Net reverse BTBT detailed-balance ansatz: zero at equilibrium r=0.
    balance=-np.expm1(-r/VT)
    bbj=f_interp(r+(p[19] if p.shape[0]>19 else 0.),rg,fg[1])*balance
    eg=max((u+r-vg-.3-1.12+phi_gidl)/(lg*1e-7),0.)
    depth=min(np.sqrt(2*eps*1.12/(Q*7e19)),TSI_M*100)
    volume=WIDTH_M*100*5e-7*depth
    gidl=Q*volume*BB_A*eg**2.5*np.exp(-BB_B/max(eg,1.))*balance
    drain=seed+ii+bbj+gidl+ch+ii_ch+iph+ii_ph+iloc
    net=ii+ii_ch+bbj+gidl+iph+ii_ph+iloc-diff-bulk-junction
    vd=u+r+VT*hole_drop_over_VT+(rc+racc)*drain
    qpair=Q*AREA_CM2*length*avg
    qaccess=Q*(WIDTH_M*100*ta*1e-7)*(la*1e-7)*avg
    charge=COX_F*u+qpair+qaccess
    return np.array([vd,drain,net,seed,emitter,bulk,diff,junction,bbj,gidl,delta/na,length,racc,charge,ws,wd,ch,VT*hole_drop_over_VT,iph])

@njit(cache=True)
def curve_grid(p,na,vbi,rg,fg,table,ug):
    out=np.empty((len(ug),21));count=0
    eps=11.7*EPS0/100
    for u in ug:
        if u==0:
            z=components(0.,0.,p,na,vbi,rg,fg,table)
            out[count,:17]=z[:17];out[count,17]=0.;out[count,18]=0.;out[count,20]=z[17]
            out[count,19]=np.sqrt(2*Q*na*vbi/eps)
            count+=1;continue
        prod=NI_CM3**2*np.expm1(u/VT)
        delta=2*prod/(na+np.sqrt(na*na+4*prod))
        source_barrier=vbi-u+VT*np.log1p(delta/na)
        if source_barrier<=0:continue
        ws=np.sqrt(2*eps*source_barrier/(Q*na))
        lavail=LENGTH_M*100-ws-1.01e-7
        if lavail<=0:continue
        rgeo=Q*na*lavail*lavail/(2*eps)-vbi
        hi=min(rg[-1],rgeo);lo=0.
        if hi<=0:continue
        a=components(u,lo,p,na,vbi,rg,fg,table)
        b=components(u,hi,p,na,vbi,rg,fg,table)
        if not np.isfinite(a[2]) or a[2]>0 or (np.isfinite(b[2]) and b[2]<0):continue
        loglo=np.log(1e-100);loghi=np.log(hi)
        for _ in range(29):
            mid=np.exp((loglo+loghi)/2)
            z=components(u,mid,p,na,vbi,rg,fg,table)
            if not np.isfinite(z[2]) or z[2]>0:loghi=np.log(mid)
            else:loglo=np.log(mid)
        r=np.exp((loglo+loghi)/2)
        z=components(u,r,p,na,vbi,rg,fg,table)
        if not np.isfinite(z[2]) or abs(z[2])>1e-5*max(z[1],1e-25):continue
        out[count,:17]=z[:17];out[count,17]=u;out[count,18]=r;out[count,20]=z[17]
        out[count,19]=np.sqrt(2*Q*na*(vbi+r)/eps)
        count+=1
    return out[:count]

def state_grid(points=201):
    # Deep equilibrium branch must be resolved in injection potential, not
    # filled by a line from zero to the first measurable-bias state.
    return np.unique(np.r_[0.,np.geomspace(1e-80,.02,121),np.linspace(.02,1.12,points)])
UG=state_grid()

def load_transport_table(force=False):
    # The current-carrying kernel solves transport directly; pair table is unused.
    return np.empty((1,1,3)),dict(action='no_transport_table_required',seconds=0.,shape=[1,1,3])

class FastModel:
    def __init__(self,na,table):
        start=time.perf_counter();f=Field(na)
        self.na=na;self.vbi=float(f.vbi);self.rg=f.rr
        self.fg=np.array([f.gain(f.rr),f.btbt(f.rr)])
        self.table=table;self.field_initialization_s=time.perf_counter()-start
    def branch(self,p,ug=UG):
        if len(ug)>3:
            gap=np.geomspace(1e-7,.02,17)
            ug=np.unique(np.r_[ug,self.vbi-gap,self.vbi,self.vbi+gap])
            ug=ug[(ug>=0)&(ug<=1.12)]
        return curve_grid(np.asarray(p,float),self.na,self.vbi,self.rg,self.fg,self.table,ug)
    def classify(self,p,ug=UG):
        b=self.branch(p,ug)
        if len(b)<8:return None
        dv=np.diff(b[:,0]);mx=np.flatnonzero((dv[:-1]>0)&(dv[1:]<0))+1
        mn=np.flatnonzero((dv[:-1]<0)&(dv[1:]>0))+1
        if not len(mx) or not len(mn):return None
        i=int(mx[0]);after=mn[mn>i]
        if not len(after):return None
        # During optimization the topology may have intermediate folds. Use the
        # terminal stable branch; the validation report counts all extrema.
        j=int(after[-1]);folds=[]
        for ind in [i,j]:
            xx=b[ind-1:ind+2,17]-b[ind,17];co=np.polyfit(xx,b[ind-1:ind+2,0],2)
            v=float(np.polyval(co,-co[1]/(2*co[0])))
            folds.append(v)
        return b,i,j,np.array(folds)
    def double_curve(self,p,points=131):
        # New physical branch and folds on every call; interpolation only maps its
        # monotonic equilibrium segments to the requested terminal voltage grid.
        cb=self.classify(p,state_grid(points))
        if cb is None:raise ValueError('No two-fold branch')
        b,i,j,fold=cb
        v=np.r_[np.linspace(0,4,401),np.linspace(3.99,0,400)]
        output=np.full((801,4),np.nan);output[:,0]=v
        low=b[:i+1];high=b[j:]
        for ind,on in [(i,False),(j,True)]:
            xx=b[ind-1:ind+2,17]-b[ind,17]
            co=np.polyfit(xx,b[ind-1:ind+2,0],2)
            uf=b[ind,17]-co[1]/(2*co[0])
            rr=self.branch(p,np.array([uf]))
            if len(rr):
                if not on and rr[0,0]>low[-1,0]:low=np.vstack([low,rr])
                if on and rr[0,0]<high[0,0]:high=np.vstack([rr,high])
        for on,part in [(False,low),(True,high)]:
            wanted=np.where(np.arange(801)<=400,v>fold[0],v>=fold[1])==on
            wanted&=(v>=part[0,0])&(v<=part[-1,0])
            output[wanted,1]=np.maximum(np.exp(np.interp(v[wanted],part[:,0],np.log(np.maximum(part[:,1],1e-300))))-1e-300,0.)
            output[wanted,2]=np.interp(v[wanted],part[:,0],part[:,17])
            output[wanted,3]=np.interp(v[wanted],part[:,0],part[:,18])
        # Equilibrium is an analytic boundary of the same equations, all net sources zero.
        output[v==0]=[0.,0.,0.,0.]
        return output,fold

    def validity_flags(self,output):
        prod=NI_CM3**2*np.expm1(output[:,2]/VT)
        delta=2*prod/(self.na+np.sqrt(self.na*self.na+4*prod))
        barrier=self.vbi-output[:,2]+VT*np.log1p(delta/self.na)
        return dict(numerically_missing=int(np.sum(~np.isfinite(output[:,1]))),
                    source_flatband_or_beyond=int(np.sum(barrier<=0)),
                    minimum_source_electrostatic_barrier_V=float(np.nanmin(barrier)),
                    max_source_injection_potential_V=float(np.nanmax(output[:,2])),
                    source_built_in_V=self.vbi)

@njit(cache=True)
def sample_root(vd,ulo,uhi,p,na,vbi,rg,fg,table):
    # Nested u/r solve using branch brackets; avoids implicit state interpolation.
    last=np.zeros(20)
    for _ in range(13):
        u=(ulo+uhi)/2;grid=curve_grid(p,na,vbi,rg,fg,table,np.array([u]))
        if len(grid)==0:return np.full(20,np.nan)
        last=grid[0]
        if last[0]>vd:uhi=u
        else:ulo=u
    return last

